name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@ecadlabs'

      - name: Install dependencies
        run: rm -f package-lock.json && npm install --ignore-scripts

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Publish packages
        run: git stash -- package-lock.json && npx lerna publish from-package --yes --no-git-tag-version --no-push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
